### ISSUE TITLE
Comment 1

### ISSUE THREAD

**Issue by kevinng250** [mjs94NJIT/project2#1]
Rather than checking every node in the graph for each node o(n^2). It may be more efficient to check each possible neighbor for each node which may be o(n).

https://github.com/mjs94NJIT/project2/blob/c428fd743aaeaef6c0936629784bc97120b7f95e/when_you_wish_upon_astar.py#L64-L69

**Comment by mjs94NJIT** [comment]
resolved in https://github.com/mjs94NJIT/project2/commit/198c1a9ad2d1032cd0ab8522b4782f058c8edde8
